/* bib_code_points values */
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (1, 'habitat', 'A', '0', 'A', 'A0_A', 'Forêt (arbres > 5m de hauteur)', 'Forêt (arbres > 5m de hauteur)');
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (2, 'habitat', 'A', '1', '1', 'A1_1', 'Feuillus', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (3, 'habitat', 'A', '1', '2', 'A1_2', 'Conifères', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (4, 'habitat', 'A', '1', '3', 'A1_3', 'Mixte (> 10% de chaque)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (5, 'habitat', 'A', '2', '1', 'A2_1', 'Semi-naturelle ou âges mélangés', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (6, 'habitat', 'A', '2', '10', 'A2_10', 'Bois mort présent', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (7, 'habitat', 'A', '2', '11', 'A2_11', 'Bois mort absent', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (8, 'habitat', 'A', '2', '2', 'A2_2', 'Plantation équienne', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (9, 'habitat', 'A', '2', '3', 'A2_3', 'Plantation non-équienne', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (10, 'habitat', 'A', '2', '4', 'A2_4', 'Plantation mâture (> 10m de haut)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (11, 'habitat', 'A', '2', '5', 'A2_5', 'Jeune plantation (5-10m)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (12, 'habitat', 'A', '2', '6', 'A2_6', 'Parc (arbres éparses et prairies)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (13, 'habitat', 'A', '2', '7', 'A2_7', 'Sous-bois dense', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (14, 'habitat', 'A', '2', '8', 'A2_8', 'Sous-bois modéré', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (15, 'habitat', 'A', '2', '9', 'A2_9', 'Sous-bois éparse', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (16, 'habitat', 'A', '3', '1', 'A3_1', 'Chêne', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (17, 'habitat', 'A', '3', '10', 'A3_10', 'Autre essence conifère', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (18, 'habitat', 'A', '3', '11', 'A3_11', 'Autre essence', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (19, 'habitat', 'A', '3', '2', 'A3_2', 'Hêtre', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (20, 'habitat', 'A', '3', '3', 'A3_3', 'Erable', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (21, 'habitat', 'A', '3', '4', 'A3_4', 'Châtaignier', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (22, 'habitat', 'A', '3', '5', 'A3_5', 'Autre essence feuillue', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (23, 'habitat', 'A', '3', '6', 'A3_6', 'Sapin', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (24, 'habitat', 'A', '3', '7', 'A3_7', 'Epicéa', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (25, 'habitat', 'A', '3', '8', 'A3_8', 'Pin', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (26, 'habitat', 'A', '3', '9', 'A3_9', 'Mélèze', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (27, 'habitat', 'B', '0', 'B', 'B0_B', 'Buissons (ou jeune forêt < 5m de hauteur)', 'Buissons (ou jeune forêt < 5m de hauteur)');
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (28, 'habitat', 'B', '1', '1', 'B1_1', 'Forêt de régénération', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (29, 'habitat', 'B', '1', '2', 'B1_2', 'Buissons calcicoles', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (30, 'habitat', 'B', '1', '3', 'B1_3', 'Lande', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (31, 'habitat', 'B', '1', '4', 'B1_4', 'Jeune taillis', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (32, 'habitat', 'B', '1', '5', 'B1_5', 'Nouvelle plantation', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (33, 'habitat', 'B', '1', '6', 'B1_6', 'Coupe « à blanc »', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (34, 'habitat', 'B', '1', '6', 'B1_6', 'Coupe « à blanc »', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (35, 'habitat', 'B', '1', '7', 'B1_7', 'Autres', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (36, 'habitat', 'B', '2', '1', 'B2_1', 'Feuillus', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (37, 'habitat', 'B', '2', '2', 'B2_2', 'Conifères', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (38, 'habitat', 'B', '2', '3', 'B2_3', 'Mixte (10% de chaque)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (39, 'habitat', 'B', '2', '4', 'B2_4', 'Buissons feuillus de marais', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (40, 'habitat', 'B', '2', '5', 'B2_5', 'Buissons conifères de marais', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (41, 'habitat', 'B', '2', '6', 'B2_6', 'Buissons mixtes de marais', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (42, 'habitat', 'B', '2', '7', 'B2_7', 'Feuilles persistantes', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (43, 'habitat', 'B', '2', '8', 'B2_8', 'Garrigue', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (44, 'habitat', 'B', '2', '9', 'B2_9', 'Maquis', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (45, 'habitat', 'B', '3', '1', 'B3_1', 'Surtout grands (3-5 mètres)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (46, 'habitat', 'B', '3', '2', 'B3_2', 'Surtout petits (1-3 mètres)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (47, 'habitat', 'B', '3', '3', 'B3_3', 'Sous-bois dense', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (48, 'habitat', 'B', '3', '4', 'B3_4', 'Sous-bois modéré', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (49, 'habitat', 'B', '3', '5', 'B3_5', 'Sous-bois éparse', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (50, 'habitat', 'B', '3', '6', 'B3_6', 'Fougères', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (51, 'habitat', 'B', '3', '7', 'B3_7', 'Pâturé', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (52, 'habitat', 'C', '0', 'C', 'C0_C', 'Pelouses, marais et landes', 'Pelouses, marais et landes');
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (53, 'habitat', 'C', '1', '1', 'C1_1', 'Pelouse calcaire sèche', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (54, 'habitat', 'C', '1', '10', 'C1_10', 'Tourbières', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (55, 'habitat', 'C', '1', '11', 'C1_11', 'Marais salés', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (56, 'habitat', 'C', '1', '11', 'C1_11', 'Marais salé', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (57, 'habitat', 'C', '1', '2', 'C1_2', 'Lande herbacée', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (58, 'habitat', 'C', '1', '3', 'C1_3', 'Lande de bruyère', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (59, 'habitat', 'C', '1', '4', 'C1_4', 'Pelouse humide naturelle', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (60, 'habitat', 'C', '1', '5', 'C1_5', 'Autres pelouses sèches', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (61, 'habitat', 'C', '1', '6', 'C1_6', 'Pelouse inondée/marais pâturé', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (62, 'habitat', 'C', '1', '7', 'C1_7', 'Roselière', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (63, 'habitat', 'C', '1', '8', 'C1_8', 'Autres marais ouverts', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (64, 'habitat', 'C', '1', '9', 'C1_9', 'Marais salants', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (65, 'habitat', 'C', '2', '1', 'C2_1', 'Haies avec arbres', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (66, 'habitat', 'C', '2', '2', 'C2_2', 'Haies sans arbres', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (67, 'habitat', 'C', '2', '3', 'C2_3', 'Lignes d’arbres sans haie', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (68, 'habitat', 'C', '2', '3', 'C2_3', 'Ligne d’arbres sans haie', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (69, 'habitat', 'C', '2', '4', 'C2_4', 'Autre limite de terrain (mur, fossé...)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (70, 'habitat', 'C', '2', '4', 'C2_4', 'Autre limite de terrain (mur, fossé…)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (71, 'habitat', 'C', '2', '5', 'C2_5', 'Groupes isolés de 1-10 arbres', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (72, 'habitat', 'C', '2', '5', 'C2_5', 'Groupe isolé de 1-10 arbres', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (73, 'habitat', 'C', '2', '6', 'C2_6', 'Pas de haie', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (74, 'habitat', 'C', '2', '7', 'C2_7', 'Montagne', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (75, 'habitat', 'C', '2', '8', 'C2_8', 'Digue', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (76, 'habitat', 'C', '3', '1', 'C3_1', 'Non pâturé', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (77, 'habitat', 'C', '3', '2', 'C3_2', 'Pâturé', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (78, 'habitat', 'C', '3', '3', 'C3_3', 'Foin', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (79, 'habitat', 'C', '3', '4', 'C3_4', 'Beaucoup de fougères', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (80, 'habitat', 'D', '0', 'D', 'D0_D', 'Milieux agricoles', 'Milieux agricoles');
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (81, 'habitat', 'D', '1', '1', 'D1_1', 'Prairie cultivée', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (82, 'habitat', 'D', '1', '2', 'D1_2', 'Prairie non cultivée', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (83, 'habitat', 'D', '1', '3', 'D1_3', 'Mixité prairie / cultures', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (84, 'habitat', 'D', '1', '4', 'D1_4', 'Grandes cultures', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (85, 'habitat', 'D', '1', '5', 'D1_5', 'Verger / vignes / maraîchers', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (86, 'habitat', 'D', '1', '6', 'D1_6', 'Autres types de cultures', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (87, 'habitat', 'D', '2', '1', 'D2_1', 'Haies avec arbres', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (88, 'habitat', 'D', '2', '2', 'D2_2', 'Haies sans arbres', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (89, 'habitat', 'D', '2', '3', 'D2_3', 'Ligne d’arbres sans haie', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (90, 'habitat', 'D', '2', '4', 'D2_4', 'Autre limite de terrain (mur, fossé…)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (91, 'habitat', 'D', '2', '4', 'D2_4', 'Autre limite de terrain', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (92, 'habitat', 'D', '2', '5', 'D2_5', 'Groupe isolé de 1-10 arbres', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (93, 'habitat', 'D', '2', '5', 'D2_5', 'Groupes isolés de 1-10 arbres', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (94, 'habitat', 'D', '2', '6', 'D2_6', 'Cour de ferme, basse-cour', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (95, 'habitat', 'D', '2', '7', 'D2_7', 'Pas de haie', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (96, 'habitat', 'D', '3', '1', 'D3_1', 'Non pâturé', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (97, 'habitat', 'D', '3', '10', 'D3_10', 'Rizières', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (98, 'habitat', 'D', '3', '2', 'D3_2', 'Pâturé', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (99, 'habitat', 'D', '3', '3', 'D3_3', 'Céréales', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (100, 'habitat', 'D', '3', '4', 'D3_4', 'Maïs', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (101, 'habitat', 'D', '3', '5', 'D3_5', 'Tournesol', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (102, 'habitat', 'D', '3', '6', 'D3_6', 'Colza', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (103, 'habitat', 'D', '3', '7', 'D3_7', 'Cultures à racines', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (104, 'habitat', 'D', '3', '8', 'D3_8', 'Sol nu', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (105, 'habitat', 'D', '3', '9', 'D3_9', 'Autres cultures', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (106, 'habitat', 'E', '0', 'E', 'E0_E', 'Milieux bâtis ou urbanisés', 'Milieux bâtis ou urbanisés');
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (107, 'habitat', 'E', '1', '1', 'E1_1', 'Urbain', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (108, 'habitat', 'E', '1', '2', 'E1_2', 'Suburbain', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (109, 'habitat', 'E', '1', '3', 'E1_3', 'Rural', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (110, 'habitat', 'E', '2', '1', 'E2_1', 'Bâtiments', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (111, 'habitat', 'E', '2', '2', 'E2_2', 'Jardins', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (112, 'habitat', 'E', '2', '3', 'E2_3', 'Parcs municipaux, zones de loisirs', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (113, 'habitat', 'E', '2', '4', 'E2_4', 'Traitement des eaux urbaines', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (114, 'habitat', 'E', '2', '5', 'E2_5', 'Près d’une route (< 50 mètres)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (115, 'habitat', 'E', '2', '5', 'E2_5', 'Près d’une route (<50 mètres)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (116, 'habitat', 'E', '2', '6', 'E2_6', 'Près d’une voie de chemin de fer (<50 mètres)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (117, 'habitat', 'E', '2', '6', 'E2_6', 'Près d’une voie de chemin de fer (< 50 mètres)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (118, 'habitat', 'E', '2', '7', 'E2_7', 'Décharge d’ordures', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (119, 'habitat', 'E', '3', '1', 'E3_1', 'Industriel', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (120, 'habitat', 'E', '3', '2', 'E3_2', 'Résidentiel', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (121, 'habitat', 'E', '3', '3', 'E3_3', 'Beaucoup d’arbres', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (122, 'habitat', 'E', '3', '4', 'E3_4', 'Peu d’arbres', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (123, 'habitat', 'E', '3', '5', 'E3_5', 'Grande surface de jardins (> 450m2)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (124, 'habitat', 'E', '3', '6', 'E3_6', 'Moyenne surface de jardins (100 - 450 m2)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (125, 'habitat', 'E', '3', '6', 'E3_6', 'Moyenne surface de jardins (100-450m²)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (126, 'habitat', 'E', '3', '7', 'E3_7', 'Faible surface de jardins (< 100 m2)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (127, 'habitat', 'E', '3', '7', 'E3_7', 'Faible surface de jardins (<100m²)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (128, 'habitat', 'E', '3', '8', 'E3_8', 'Beaucoup de buissons', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (129, 'habitat', 'E', '3', '9', 'E3_9', 'Peu de buissons', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (130, 'habitat', 'F', '0', 'F', 'F0_F', 'Milieux aquatiques', 'Milieux aquatiques');
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (131, 'habitat', 'F', '4', '1', 'F4_1', 'Non utilisé/non perturbé', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (132, 'habitat', 'F', '4', '1', 'F4_1', 'Mare (moins de 50 m2)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (133, 'habitat', 'F', '4', '1', 'F4_1', 'Eutrophique (eau verte)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (134, 'habitat', 'F', '4', '10', 'F4_10', 'Grand canal (> 5m de largeur)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (135, 'habitat', 'F', '4', '10', 'F4_10', 'Rives avec végétation', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (136, 'habitat', 'F', '4', '11', 'F4_11', 'Eaux saumâtres (salins, lagunes…)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (137, 'habitat', 'F', '4', '11', 'F4_11', 'Rives avec falaise', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (138, 'habitat', 'F', '4', '12', 'F4_12', 'Fleuve / rivière large (> 10m)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (139, 'habitat', 'F', '4', '2', 'F4_2', 'Sports nautiques', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (140, 'habitat', 'F', '4', '2', 'F4_2', 'Oligotrophique (eau claire, peu d’algues)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (141, 'habitat', 'F', '4', '2', 'F4_2', 'Petit étang (50 - 450 m2)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (142, 'habitat', 'F', '4', '3', 'F4_3', 'Lac/réservoir (berges naturelles)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (143, 'habitat', 'F', '4', '3', 'F4_3', 'Pêche à la ligne', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (144, 'habitat', 'F', '4', '3', 'F4_3', 'Dystrophique (eau noire)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (145, 'habitat', 'F', '4', '4', 'F4_4', 'Bigarré (eau claire, beaucoup dd’algues)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (146, 'habitat', 'F', '4', '4', 'F4_4', 'Bigarré (eau claire, beaucoup d’algues)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (147, 'habitat', 'F', '4', '4', 'F4_4', 'Réservoir (berges non naturelles)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (148, 'habitat', 'F', '4', '4', 'F4_4', 'Activité industrielle', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (149, 'habitat', 'F', '4', '5', 'F4_5', 'Traitements d’eaux usées', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (150, 'habitat', 'F', '4', '5', 'F4_5', 'Carrière de gravier, de sable...', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (151, 'habitat', 'F', '4', '5', 'F4_5', 'Courant faible / moyen', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (152, 'habitat', 'F', '4', '6', 'F4_6', 'Autres dérangements', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (153, 'habitat', 'F', '4', '6', 'F4_6', 'Ruisseau (< 3m de largeur)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (154, 'habitat', 'F', '4', '6', 'F4_6', 'Courant fort', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (155, 'habitat', 'F', '4', '7', 'F4_7', 'Dragué', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (156, 'habitat', 'F', '4', '7', 'F4_7', 'Activités industrielles', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (157, 'habitat', 'F', '4', '7', 'F4_7', 'Rivière (3m < largeur < 10m)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (158, 'habitat', 'F', '4', '8', 'F4_8', 'Fossé inondé (< 2m de largeur)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (159, 'habitat', 'F', '4', '8', 'F4_8', 'Non dragué', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (160, 'habitat', 'F', '4', '8', 'F4_8', 'Petites îles', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (161, 'habitat', 'F', '4', '9', 'F4_9', 'Petit canal (2 - 5m. de largeur)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (162, 'habitat', 'F', '4', '9', 'F4_9', 'Rives nues', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (163, 'habitat', 'G', '0', 'G', 'G0_G', 'Rochers terrestres ou côtiers', 'Rochers terrestres ou côtiers');
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (164, 'habitat', 'G', '1', '1', 'G1_1', 'Falaise', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (165, 'habitat', 'G', '1', '2', 'G1_2', 'Eboulis, pente rocheuse', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (166, 'habitat', 'G', '1', '3', 'G1_3', 'Pavement calcaire', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (167, 'habitat', 'G', '1', '4', 'G1_4', 'Autres sols rocheux', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (168, 'habitat', 'G', '1', '5', 'G1_5', 'Carrière', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (169, 'habitat', 'G', '1', '6', 'G1_6', 'Mine / abîme / terril', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (170, 'habitat', 'G', '1', '7', 'G1_7', 'Grotte', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (171, 'habitat', 'G', '1', '8', 'G1_8', 'Dune', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (172, 'habitat', 'G', '2', '1', 'G2_1', 'Montagne', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (173, 'habitat', 'G', '2', '2', 'G2_2', 'Pas en montagne', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (174, 'habitat', 'G', '2', '3', 'G2_3', 'Bord de mer', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (175, 'habitat', 'G', '2', '4', 'G2_4', 'Fort dérangement par l’homme (grimpeurs, promeneurs…)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (176, 'habitat', 'G', '2', '4', 'G2_4', 'Fort dérangement par l’homme (grimpeurs, promeneurs...)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (177, 'habitat', 'G', '3', '1', 'G3_1', 'Roche nue', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (178, 'habitat', 'G', '3', '2', 'G3_2', 'Végétation basse présente (mousses, lichens…)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (179, 'habitat', 'G', '3', '2', 'G3_2', 'Végétation basse présente (mousses, lichens...)', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (180, 'habitat', 'G', '3', '3', 'G3_3', 'Graminées présentes', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (181, 'habitat', 'G', '3', '4', 'G3_4', 'Buissons présents', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (185, 'pluie', null, null, '1', 'NO_RAIN', 'Absente', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (186, 'pluie', null, null, '2', 'SMALL_RAIN', 'Bruine', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (187, 'pluie', null, null, '3', 'STRONG_RAIN', 'Averses', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (188, 'vent', null, null, '1', 'NO_WIND', 'Absent', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (183, 'nuage', null, null, '2', 'TWO_THIRD', '33-66 %', '33 – 66%');
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (182, 'nuage', null, null, '1', 'ONE_THIRD', '0-33 %', '0 – 33%');
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (184, 'nuage', null, null, '3', 'THREE_THIRD', '66-100 %', '66 – 100%');
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (190, 'vent', null, null, '3', 'MIDDLE_STRONG_WIND', 'Moyen à fort', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (189, 'vent', null, null, '2', 'WEAK_WIND', 'Faible', null);
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (191, 'visibilité', null, null, '1', 'GOOD_VISIBILITY', 'Bonne', 'Bonne');
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (193, 'visibilité', null, null, '3', 'BAD_VISIBILITY', 'Faible', 'Faible');
INSERT INTO pr_stoc.bib_code_points (id, type_code, principal, colonne, code, code_vn, libelle, libelle_vn) VALUES (192, 'visibilité', null, null, '2', 'MODERATE_VISIBILITY', 'Modérée', 'Visibilité modérée');


/* bib_code_dist values */

